updated logs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,7 +15,7 @@ jobs:
         docker build . -t $REPO_NAME/$IMAGE_NAME
     - name: run docker
       run: |
-        docker compose up --detach   && \
+        docker compose up   && \
           docker ps && sleep 5
     
     - name: Output container logs
@@ -43,6 +43,14 @@ jobs:
         reporters: cli
         bail: true
 
+    - name: Output Newman Test Results
+      run: |
+          if [ -f newman_output.json ]; then
+            cat newman_output.json  # Output the test results to the workflow logs
+          else
+            echo "Newman output file not found."
+            exit 1
+          fi
     - name: Check if we failed
       id: fail-check
       shell: bash
